import {
  ArrowRight,
  Code,
  Globe,
  Image,
  Layers,
  LayoutGrid,
  Repeat,
  Rocket,
  Server,
  Zap,
} from "lucide-react";
export const concepts = [
  {
    title: "Server Components",
    description:
      "Learn about React Server Components and how they work in Next.js",
    icon: Server,
    href: "/next-concepts/server-components",
    color: "bg-blue-500/10",
    textColor: "text-blue-500",
  },
  {
    title: "Data Fetching",
    description: "Explore different data fetching patterns in Next.js",
    icon: Repeat,
    href: "/next-concepts/data-fetching",
    color: "bg-green-500/10",
    textColor: "text-green-500",
  },
  {
    title: "Rendering Strategies",
    description: "Understand SSG, SSR, and ISR rendering approaches",
    icon: Layers,
    href: "/rendering-strategies",
    color: "bg-purple-500/10",
    textColor: "text-purple-500",
  },
  {
    title: "Caching & Revalidation",
    description: "Learn how Next.js caches data and how to revalidate it",
    icon: Rocket,
    href: "/next-concepts/caching",
    color: "bg-orange-500/10",
    textColor: "text-orange-500",
  },
  {
    title: "Routing & Layouts",
    description:
      "Master Next.js App Router, layouts, and advanced routing patterns",
    icon: LayoutGrid,
    href: "/next-concepts/routing",
    color: "bg-pink-500/10",
    textColor: "text-pink-500",
  },
  {
    title: "Optimization",
    description: "Optimize your Next.js application for performance",
    icon: Zap,
    href: "/next-concepts/optimization",
    color: "bg-yellow-500/10",
    textColor: "text-yellow-500",
  },
  {
    title: "Image & Fonts",
    description: "Use Next.js built-in image and font optimization",
    icon: Image,
    href: "/next-concepts/image-fonts",
    color: "bg-indigo-500/10",
    textColor: "text-indigo-500",
  },
  {
    title: "Internationalization",
    description: "Add multi-language support to your Next.js application",
    icon: Globe,
    href: "/next-concepts/i18n",
    color: "bg-teal-500/10",
    textColor: "text-teal-500",
  },
  {
    title: "API Routes & Middleware",
    description: "Create API endpoints and use middleware in Next.js",
    icon: Code,
    href: "/next-concepts/api-middleware",
    color: "bg-red-500/10",
    textColor: "text-red-500",
  },
];
